/**
 * OrderCloud
 * OrderCloud is an awesome C# platform API for making eCommerce applications. It is NOT a complete solution. It's designed to be used as the backend component with various other integrations and services.
 *
 * OpenAPI spec version: 1.0.89
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.PaymentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentApi', function() {
    describe('createTransactionV1ordersdirectionorderIDpaymentspaymentIDtransactions', function() {
      it('should call createTransactionV1ordersdirectionorderIDpaymentspaymentIDtransactions successfully', function(done) {
        //uncomment below and update the code to test createTransactionV1ordersdirectionorderIDpaymentspaymentIDtransactions
        //instance.createTransactionV1ordersdirectionorderIDpaymentspaymentIDtransactions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createV1ordersdirectionorderIDpayments', function() {
      it('should call createV1ordersdirectionorderIDpayments successfully', function(done) {
        //uncomment below and update the code to test createV1ordersdirectionorderIDpayments
        //instance.createV1ordersdirectionorderIDpayments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTransactionV1ordersdirectionorderIDpaymentspaymentIDtransactionstransactionID', function() {
      it('should call deleteTransactionV1ordersdirectionorderIDpaymentspaymentIDtransactionstransactionID successfully', function(done) {
        //uncomment below and update the code to test deleteTransactionV1ordersdirectionorderIDpaymentspaymentIDtransactionstransactionID
        //instance.deleteTransactionV1ordersdirectionorderIDpaymentspaymentIDtransactionstransactionID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteV1ordersdirectionorderIDpaymentspaymentID', function() {
      it('should call deleteV1ordersdirectionorderIDpaymentspaymentID successfully', function(done) {
        //uncomment below and update the code to test deleteV1ordersdirectionorderIDpaymentspaymentID
        //instance.deleteV1ordersdirectionorderIDpaymentspaymentID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1ordersdirectionorderIDpaymentspaymentID', function() {
      it('should call getV1ordersdirectionorderIDpaymentspaymentID successfully', function(done) {
        //uncomment below and update the code to test getV1ordersdirectionorderIDpaymentspaymentID
        //instance.getV1ordersdirectionorderIDpaymentspaymentID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listV1ordersdirectionorderIDpayments', function() {
      it('should call listV1ordersdirectionorderIDpayments successfully', function(done) {
        //uncomment below and update the code to test listV1ordersdirectionorderIDpayments
        //instance.listV1ordersdirectionorderIDpayments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchV1ordersdirectionorderIDpaymentspaymentID', function() {
      it('should call patchV1ordersdirectionorderIDpaymentspaymentID successfully', function(done) {
        //uncomment below and update the code to test patchV1ordersdirectionorderIDpaymentspaymentID
        //instance.patchV1ordersdirectionorderIDpaymentspaymentID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
