/**
 * OrderCloud
 * OrderCloud is an awesome C# platform API for making eCommerce applications. It is NOT a complete solution. It's designed to be used as the backend component with various other integrations and services.
 *
 * OpenAPI spec version: 1.0.89
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.Order();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Order', function() {
    it('should create an instance of Order', function() {
      // uncomment below and update the code to test Order
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be.a(OrderCloud.Order);
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property fromUser (base name: "FromUser")', function() {
      // uncomment below and update the code to test the property fromUser
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property fromCompanyID (base name: "FromCompanyID")', function() {
      // uncomment below and update the code to test the property fromCompanyID
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property fromUserID (base name: "FromUserID")', function() {
      // uncomment below and update the code to test the property fromUserID
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property billingAddressID (base name: "BillingAddressID")', function() {
      // uncomment below and update the code to test the property billingAddressID
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property billingAddress (base name: "BillingAddress")', function() {
      // uncomment below and update the code to test the property billingAddress
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property shippingAddressID (base name: "ShippingAddressID")', function() {
      // uncomment below and update the code to test the property shippingAddressID
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property comments (base name: "Comments")', function() {
      // uncomment below and update the code to test the property comments
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property lineItemCount (base name: "LineItemCount")', function() {
      // uncomment below and update the code to test the property lineItemCount
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "Status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property dateCreated (base name: "DateCreated")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property dateSubmitted (base name: "DateSubmitted")', function() {
      // uncomment below and update the code to test the property dateSubmitted
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property dateApproved (base name: "DateApproved")', function() {
      // uncomment below and update the code to test the property dateApproved
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property dateDeclined (base name: "DateDeclined")', function() {
      // uncomment below and update the code to test the property dateDeclined
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property dateCanceled (base name: "DateCanceled")', function() {
      // uncomment below and update the code to test the property dateCanceled
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property dateCompleted (base name: "DateCompleted")', function() {
      // uncomment below and update the code to test the property dateCompleted
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property subtotal (base name: "Subtotal")', function() {
      // uncomment below and update the code to test the property subtotal
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property shippingCost (base name: "ShippingCost")', function() {
      // uncomment below and update the code to test the property shippingCost
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property taxCost (base name: "TaxCost")', function() {
      // uncomment below and update the code to test the property taxCost
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property promotionDiscount (base name: "PromotionDiscount")', function() {
      // uncomment below and update the code to test the property promotionDiscount
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property total (base name: "Total")', function() {
      // uncomment below and update the code to test the property total
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property isSubmitted (base name: "IsSubmitted")', function() {
      // uncomment below and update the code to test the property isSubmitted
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

    it('should have the property xp (base name: "xp")', function() {
      // uncomment below and update the code to test the property xp
      //var instance = new OrderCloud.Order();
      //expect(instance).to.be();
    });

  });

}));
