/**
 * OrderCloud
 * OrderCloud is an awesome C# platform API for making eCommerce applications. It is NOT a complete solution. It's designed to be used as the backend component with various other integrations and services.
 *
 * OpenAPI spec version: 1.0.89
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ImpersonationConfig {
    'ID'?: string;
    'ImpersonationBuyerID'?: string;
    'ImpersonationGroupID'?: string;
    'ImpersonationUserID'?: string;
    'BuyerID'?: string;
    'GroupID'?: string;
    'UserID'?: string;
    'SecurityProfileID'?: string;
    'ClientID'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ID",
            "baseName": "ID",
            "type": "string"
        },
        {
            "name": "ImpersonationBuyerID",
            "baseName": "ImpersonationBuyerID",
            "type": "string"
        },
        {
            "name": "ImpersonationGroupID",
            "baseName": "ImpersonationGroupID",
            "type": "string"
        },
        {
            "name": "ImpersonationUserID",
            "baseName": "ImpersonationUserID",
            "type": "string"
        },
        {
            "name": "BuyerID",
            "baseName": "BuyerID",
            "type": "string"
        },
        {
            "name": "GroupID",
            "baseName": "GroupID",
            "type": "string"
        },
        {
            "name": "UserID",
            "baseName": "UserID",
            "type": "string"
        },
        {
            "name": "SecurityProfileID",
            "baseName": "SecurityProfileID",
            "type": "string"
        },
        {
            "name": "ClientID",
            "baseName": "ClientID",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ImpersonationConfig.attributeTypeMap;
    }
}

