/**
 * OrderCloud
 * OrderCloud is an awesome C# platform API for making eCommerce applications. It is NOT a complete solution. It's designed to be used as the backend component with various other integrations and services.
 *
 * OpenAPI spec version: 1.0.89
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PriceBreak } from './priceBreak';

export class PriceSchedule {
    'ID'?: string;
    'Name'?: string;
    'ApplyTax'?: boolean;
    'ApplyShipping'?: boolean;
    'MinQuantity'?: number;
    'MaxQuantity'?: number;
    'UseCumulativeQuantity'?: boolean;
    'RestrictedQuantity'?: boolean;
    'PriceBreaks'?: Array<PriceBreak>;
    'Xp'?: any;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ID",
            "baseName": "ID",
            "type": "string"
        },
        {
            "name": "Name",
            "baseName": "Name",
            "type": "string"
        },
        {
            "name": "ApplyTax",
            "baseName": "ApplyTax",
            "type": "boolean"
        },
        {
            "name": "ApplyShipping",
            "baseName": "ApplyShipping",
            "type": "boolean"
        },
        {
            "name": "MinQuantity",
            "baseName": "MinQuantity",
            "type": "number"
        },
        {
            "name": "MaxQuantity",
            "baseName": "MaxQuantity",
            "type": "number"
        },
        {
            "name": "UseCumulativeQuantity",
            "baseName": "UseCumulativeQuantity",
            "type": "boolean"
        },
        {
            "name": "RestrictedQuantity",
            "baseName": "RestrictedQuantity",
            "type": "boolean"
        },
        {
            "name": "PriceBreaks",
            "baseName": "PriceBreaks",
            "type": "Array<PriceBreak>"
        },
        {
            "name": "Xp",
            "baseName": "xp",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PriceSchedule.attributeTypeMap;
    }
}

