export * from './addressApi';
import { AddressApi } from './addressApi';
export * from './adminAddressApi';
import { AdminAddressApi } from './adminAddressApi';
export * from './adminUserApi';
import { AdminUserApi } from './adminUserApi';
export * from './adminUserGroupApi';
import { AdminUserGroupApi } from './adminUserGroupApi';
export * from './apiClientApi';
import { ApiClientApi } from './apiClientApi';
export * from './approvalRuleApi';
import { ApprovalRuleApi } from './approvalRuleApi';
export * from './buyerApi';
import { BuyerApi } from './buyerApi';
export * from './catalogApi';
import { CatalogApi } from './catalogApi';
export * from './categoryApi';
import { CategoryApi } from './categoryApi';
export * from './costCenterApi';
import { CostCenterApi } from './costCenterApi';
export * from './creditCardApi';
import { CreditCardApi } from './creditCardApi';
export * from './impersonationConfigApi';
import { ImpersonationConfigApi } from './impersonationConfigApi';
export * from './incrementorApi';
import { IncrementorApi } from './incrementorApi';
export * from './lineItemApi';
import { LineItemApi } from './lineItemApi';
export * from './meApi';
import { MeApi } from './meApi';
export * from './messageSenderApi';
import { MessageSenderApi } from './messageSenderApi';
export * from './orderApi';
import { OrderApi } from './orderApi';
export * from './passwordResetApi';
import { PasswordResetApi } from './passwordResetApi';
export * from './paymentApi';
import { PaymentApi } from './paymentApi';
export * from './priceScheduleApi';
import { PriceScheduleApi } from './priceScheduleApi';
export * from './productApi';
import { ProductApi } from './productApi';
export * from './productFacetApi';
import { ProductFacetApi } from './productFacetApi';
export * from './promotionApi';
import { PromotionApi } from './promotionApi';
export * from './securityProfileApi';
import { SecurityProfileApi } from './securityProfileApi';
export * from './shipmentApi';
import { ShipmentApi } from './shipmentApi';
export * from './specApi';
import { SpecApi } from './specApi';
export * from './spendingAccountApi';
import { SpendingAccountApi } from './spendingAccountApi';
export * from './supplierApi';
import { SupplierApi } from './supplierApi';
export * from './supplierAddressApi';
import { SupplierAddressApi } from './supplierAddressApi';
export * from './supplierUserApi';
import { SupplierUserApi } from './supplierUserApi';
export * from './supplierUserGroupApi';
import { SupplierUserGroupApi } from './supplierUserGroupApi';
export * from './userApi';
import { UserApi } from './userApi';
export * from './userGroupApi';
import { UserGroupApi } from './userGroupApi';
export const APIS = [AddressApi, AdminAddressApi, AdminUserApi, AdminUserGroupApi, ApiClientApi, ApprovalRuleApi, BuyerApi, CatalogApi, CategoryApi, CostCenterApi, CreditCardApi, ImpersonationConfigApi, IncrementorApi, LineItemApi, MeApi, MessageSenderApi, OrderApi, PasswordResetApi, PaymentApi, PriceScheduleApi, ProductApi, ProductFacetApi, PromotionApi, SecurityProfileApi, ShipmentApi, SpecApi, SpendingAccountApi, SupplierApi, SupplierAddressApi, SupplierUserApi, SupplierUserGroupApi, UserApi, UserGroupApi];
