/**
 * OrderCloud
 * OrderCloud is an awesome C# platform API for making eCommerce applications. It is NOT a complete solution. It's designed to be used as the backend component with various other integrations and services.
 *
 * OpenAPI spec version: 1.0.89
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import localVarRequest = require('request');
import http = require('http');
import Promise = require('bluebird');

/* tslint:disable:no-unused-locals */
import { Address } from '../model/address';
import { LineItem } from '../model/lineItem';
import { ListLineItem } from '../model/listLineItem';

import { ObjectSerializer, Authentication, HttpBasicAuth, ApiKeyAuth, OAuth, VoidAuth } from '../model/models';

let defaultBasePath = 'https://api.ordercloud.io/v1';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum LineItemApiApiKeys {
}

export class LineItemApi {
    protected _basePath = defaultBasePath;
    protected defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'OAuth2': new OAuth(),
    }

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: LineItemApiApiKeys, value: string) {
        (this.authentications as any)[LineItemApiApiKeys[key]].apiKey = value;
    }

    set accessToken(token: string) {
        this.authentications.OAuth2.accessToken = token;
    }

    /**
     * 
     * @param Direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param OrderID ID of the order.
     * @param LineItem 
     */
    public createV1ordersdirectionorderIDlineitems (Direction: string, OrderID: string, LineItem: LineItem) : Promise<{ response: http.ClientResponse; body: LineItem;  }> {
        const localVarPath = this.basePath + '/orders/{direction}/{orderID}/lineitems'
            .replace('{' + 'direction' + '}', encodeURIComponent(String(Direction)))
            .replace('{' + 'orderID' + '}', encodeURIComponent(String(OrderID)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'Direction' is not null or undefined
        if (Direction === null || Direction === undefined) {
            throw new Error('Required parameter Direction was null or undefined when calling createV1ordersdirectionorderIDlineitems.');
        }

        // verify required parameter 'OrderID' is not null or undefined
        if (OrderID === null || OrderID === undefined) {
            throw new Error('Required parameter OrderID was null or undefined when calling createV1ordersdirectionorderIDlineitems.');
        }

        // verify required parameter 'LineItem' is not null or undefined
        if (LineItem === null || LineItem === undefined) {
            throw new Error('Required parameter LineItem was null or undefined when calling createV1ordersdirectionorderIDlineitems.');
        }


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(LineItem, "LineItem")
        };

        this.authentications.OAuth2.applyToRequest(localVarRequestOptions);

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body: LineItem;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "LineItem");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
    /**
     * 
     * @param Direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param OrderID ID of the order.
     * @param LineItemID ID of the line item.
     */
    public deleteV1ordersdirectionorderIDlineitemslineItemID (Direction: string, OrderID: string, LineItemID: string) : Promise<{ response: http.ClientResponse; body?: any;  }> {
        const localVarPath = this.basePath + '/orders/{direction}/{orderID}/lineitems/{lineItemID}'
            .replace('{' + 'direction' + '}', encodeURIComponent(String(Direction)))
            .replace('{' + 'orderID' + '}', encodeURIComponent(String(OrderID)))
            .replace('{' + 'lineItemID' + '}', encodeURIComponent(String(LineItemID)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'Direction' is not null or undefined
        if (Direction === null || Direction === undefined) {
            throw new Error('Required parameter Direction was null or undefined when calling deleteV1ordersdirectionorderIDlineitemslineItemID.');
        }

        // verify required parameter 'OrderID' is not null or undefined
        if (OrderID === null || OrderID === undefined) {
            throw new Error('Required parameter OrderID was null or undefined when calling deleteV1ordersdirectionorderIDlineitemslineItemID.');
        }

        // verify required parameter 'LineItemID' is not null or undefined
        if (LineItemID === null || LineItemID === undefined) {
            throw new Error('Required parameter LineItemID was null or undefined when calling deleteV1ordersdirectionorderIDlineitemslineItemID.');
        }


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        this.authentications.OAuth2.applyToRequest(localVarRequestOptions);

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body?: any;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
    /**
     * 
     * @param Direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param OrderID ID of the order.
     * @param LineItemID ID of the line item.
     */
    public getV1ordersdirectionorderIDlineitemslineItemID (Direction: string, OrderID: string, LineItemID: string) : Promise<{ response: http.ClientResponse; body: LineItem;  }> {
        const localVarPath = this.basePath + '/orders/{direction}/{orderID}/lineitems/{lineItemID}'
            .replace('{' + 'direction' + '}', encodeURIComponent(String(Direction)))
            .replace('{' + 'orderID' + '}', encodeURIComponent(String(OrderID)))
            .replace('{' + 'lineItemID' + '}', encodeURIComponent(String(LineItemID)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'Direction' is not null or undefined
        if (Direction === null || Direction === undefined) {
            throw new Error('Required parameter Direction was null or undefined when calling getV1ordersdirectionorderIDlineitemslineItemID.');
        }

        // verify required parameter 'OrderID' is not null or undefined
        if (OrderID === null || OrderID === undefined) {
            throw new Error('Required parameter OrderID was null or undefined when calling getV1ordersdirectionorderIDlineitemslineItemID.');
        }

        // verify required parameter 'LineItemID' is not null or undefined
        if (LineItemID === null || LineItemID === undefined) {
            throw new Error('Required parameter LineItemID was null or undefined when calling getV1ordersdirectionorderIDlineitemslineItemID.');
        }


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        this.authentications.OAuth2.applyToRequest(localVarRequestOptions);

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body: LineItem;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "LineItem");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
    /**
     * 
     * @param Direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param OrderID ID of the order.
     * @param Search Word or phrase to search for.
     * @param SearchOn Comma-delimited list of fields to search on.
     * @param SortBy Comma-delimited list of fields to sort by.
     * @param Page Page of results to return. Default: 1
     * @param PageSize Number of results to return per page. Default: 20, max: 100.
     * @param Filters Any additional key/value pairs passed in the query string are interpretted as filters. Valid keys are top-level properties of the returned model or &#39;xp.???&#39;
     */
    public listV1ordersdirectionorderIDlineitems (Direction: string, OrderID: string, Search?: string, SearchOn?: string, SortBy?: string, Page?: number, PageSize?: number, Filters?: any) : Promise<{ response: http.ClientResponse; body: ListLineItem;  }> {
        const localVarPath = this.basePath + '/orders/{direction}/{orderID}/lineitems'
            .replace('{' + 'direction' + '}', encodeURIComponent(String(Direction)))
            .replace('{' + 'orderID' + '}', encodeURIComponent(String(OrderID)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'Direction' is not null or undefined
        if (Direction === null || Direction === undefined) {
            throw new Error('Required parameter Direction was null or undefined when calling listV1ordersdirectionorderIDlineitems.');
        }

        // verify required parameter 'OrderID' is not null or undefined
        if (OrderID === null || OrderID === undefined) {
            throw new Error('Required parameter OrderID was null or undefined when calling listV1ordersdirectionorderIDlineitems.');
        }

        if (Search !== undefined) {
            localVarQueryParameters['search'] = ObjectSerializer.serialize(Search, "string");
        }

        if (SearchOn !== undefined) {
            localVarQueryParameters['searchOn'] = ObjectSerializer.serialize(SearchOn, "string");
        }

        if (SortBy !== undefined) {
            localVarQueryParameters['sortBy'] = ObjectSerializer.serialize(SortBy, "string");
        }

        if (Page !== undefined) {
            localVarQueryParameters['page'] = ObjectSerializer.serialize(Page, "number");
        }

        if (PageSize !== undefined) {
            localVarQueryParameters['pageSize'] = ObjectSerializer.serialize(PageSize, "number");
        }

        if (Filters !== undefined) {
            localVarQueryParameters['filters'] = ObjectSerializer.serialize(Filters, "any");
        }


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        this.authentications.OAuth2.applyToRequest(localVarRequestOptions);

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body: ListLineItem;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "ListLineItem");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
    /**
     * 
     * @param Direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param OrderID ID of the order.
     * @param LineItemID ID of the line item.
     * @param Address 
     */
    public patchShippingAddressV1ordersdirectionorderIDlineitemslineItemIDshipto (Direction: string, OrderID: string, LineItemID: string, Address: Address) : Promise<{ response: http.ClientResponse; body: LineItem;  }> {
        const localVarPath = this.basePath + '/orders/{direction}/{orderID}/lineitems/{lineItemID}/shipto'
            .replace('{' + 'direction' + '}', encodeURIComponent(String(Direction)))
            .replace('{' + 'orderID' + '}', encodeURIComponent(String(OrderID)))
            .replace('{' + 'lineItemID' + '}', encodeURIComponent(String(LineItemID)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'Direction' is not null or undefined
        if (Direction === null || Direction === undefined) {
            throw new Error('Required parameter Direction was null or undefined when calling patchShippingAddressV1ordersdirectionorderIDlineitemslineItemIDshipto.');
        }

        // verify required parameter 'OrderID' is not null or undefined
        if (OrderID === null || OrderID === undefined) {
            throw new Error('Required parameter OrderID was null or undefined when calling patchShippingAddressV1ordersdirectionorderIDlineitemslineItemIDshipto.');
        }

        // verify required parameter 'LineItemID' is not null or undefined
        if (LineItemID === null || LineItemID === undefined) {
            throw new Error('Required parameter LineItemID was null or undefined when calling patchShippingAddressV1ordersdirectionorderIDlineitemslineItemIDshipto.');
        }

        // verify required parameter 'Address' is not null or undefined
        if (Address === null || Address === undefined) {
            throw new Error('Required parameter Address was null or undefined when calling patchShippingAddressV1ordersdirectionorderIDlineitemslineItemIDshipto.');
        }


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'PATCH',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(Address, "Address")
        };

        this.authentications.OAuth2.applyToRequest(localVarRequestOptions);

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body: LineItem;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "LineItem");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
    /**
     * 
     * @param Direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param OrderID ID of the order.
     * @param LineItemID ID of the line item.
     * @param LineItem 
     */
    public patchV1ordersdirectionorderIDlineitemslineItemID (Direction: string, OrderID: string, LineItemID: string, LineItem: LineItem) : Promise<{ response: http.ClientResponse; body: LineItem;  }> {
        const localVarPath = this.basePath + '/orders/{direction}/{orderID}/lineitems/{lineItemID}'
            .replace('{' + 'direction' + '}', encodeURIComponent(String(Direction)))
            .replace('{' + 'orderID' + '}', encodeURIComponent(String(OrderID)))
            .replace('{' + 'lineItemID' + '}', encodeURIComponent(String(LineItemID)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'Direction' is not null or undefined
        if (Direction === null || Direction === undefined) {
            throw new Error('Required parameter Direction was null or undefined when calling patchV1ordersdirectionorderIDlineitemslineItemID.');
        }

        // verify required parameter 'OrderID' is not null or undefined
        if (OrderID === null || OrderID === undefined) {
            throw new Error('Required parameter OrderID was null or undefined when calling patchV1ordersdirectionorderIDlineitemslineItemID.');
        }

        // verify required parameter 'LineItemID' is not null or undefined
        if (LineItemID === null || LineItemID === undefined) {
            throw new Error('Required parameter LineItemID was null or undefined when calling patchV1ordersdirectionorderIDlineitemslineItemID.');
        }

        // verify required parameter 'LineItem' is not null or undefined
        if (LineItem === null || LineItem === undefined) {
            throw new Error('Required parameter LineItem was null or undefined when calling patchV1ordersdirectionorderIDlineitemslineItemID.');
        }


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'PATCH',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(LineItem, "LineItem")
        };

        this.authentications.OAuth2.applyToRequest(localVarRequestOptions);

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body: LineItem;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "LineItem");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
    /**
     * 
     * @param Direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param OrderID ID of the order.
     * @param LineItemID ID of the line item.
     * @param LineItem 
     */
    public saveV1ordersdirectionorderIDlineitemslineItemID (Direction: string, OrderID: string, LineItemID: string, LineItem: LineItem) : Promise<{ response: http.ClientResponse; body: LineItem;  }> {
        const localVarPath = this.basePath + '/orders/{direction}/{orderID}/lineitems/{lineItemID}'
            .replace('{' + 'direction' + '}', encodeURIComponent(String(Direction)))
            .replace('{' + 'orderID' + '}', encodeURIComponent(String(OrderID)))
            .replace('{' + 'lineItemID' + '}', encodeURIComponent(String(LineItemID)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'Direction' is not null or undefined
        if (Direction === null || Direction === undefined) {
            throw new Error('Required parameter Direction was null or undefined when calling saveV1ordersdirectionorderIDlineitemslineItemID.');
        }

        // verify required parameter 'OrderID' is not null or undefined
        if (OrderID === null || OrderID === undefined) {
            throw new Error('Required parameter OrderID was null or undefined when calling saveV1ordersdirectionorderIDlineitemslineItemID.');
        }

        // verify required parameter 'LineItemID' is not null or undefined
        if (LineItemID === null || LineItemID === undefined) {
            throw new Error('Required parameter LineItemID was null or undefined when calling saveV1ordersdirectionorderIDlineitemslineItemID.');
        }

        // verify required parameter 'LineItem' is not null or undefined
        if (LineItem === null || LineItem === undefined) {
            throw new Error('Required parameter LineItem was null or undefined when calling saveV1ordersdirectionorderIDlineitemslineItemID.');
        }


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'PUT',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(LineItem, "LineItem")
        };

        this.authentications.OAuth2.applyToRequest(localVarRequestOptions);

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body: LineItem;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "LineItem");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
    /**
     * 
     * @param Direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param OrderID ID of the order.
     * @param LineItemID ID of the line item.
     * @param Address 
     */
    public setShippingAddressV1ordersdirectionorderIDlineitemslineItemIDshipto (Direction: string, OrderID: string, LineItemID: string, Address: Address) : Promise<{ response: http.ClientResponse; body: LineItem;  }> {
        const localVarPath = this.basePath + '/orders/{direction}/{orderID}/lineitems/{lineItemID}/shipto'
            .replace('{' + 'direction' + '}', encodeURIComponent(String(Direction)))
            .replace('{' + 'orderID' + '}', encodeURIComponent(String(OrderID)))
            .replace('{' + 'lineItemID' + '}', encodeURIComponent(String(LineItemID)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'Direction' is not null or undefined
        if (Direction === null || Direction === undefined) {
            throw new Error('Required parameter Direction was null or undefined when calling setShippingAddressV1ordersdirectionorderIDlineitemslineItemIDshipto.');
        }

        // verify required parameter 'OrderID' is not null or undefined
        if (OrderID === null || OrderID === undefined) {
            throw new Error('Required parameter OrderID was null or undefined when calling setShippingAddressV1ordersdirectionorderIDlineitemslineItemIDshipto.');
        }

        // verify required parameter 'LineItemID' is not null or undefined
        if (LineItemID === null || LineItemID === undefined) {
            throw new Error('Required parameter LineItemID was null or undefined when calling setShippingAddressV1ordersdirectionorderIDlineitemslineItemIDshipto.');
        }

        // verify required parameter 'Address' is not null or undefined
        if (Address === null || Address === undefined) {
            throw new Error('Required parameter Address was null or undefined when calling setShippingAddressV1ordersdirectionorderIDlineitemslineItemIDshipto.');
        }


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'PUT',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(Address, "Address")
        };

        this.authentications.OAuth2.applyToRequest(localVarRequestOptions);

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body: LineItem;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "LineItem");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
}
